[project]
name = "advent-of-code-25"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "advent-of-code-utils",
    "tqdm>=4.67.1",
]

[tool.uv.sources]
advent-of-code-utils = { path = "advent-of-code-utils", editable = true }
